#!/bin/bash 

#backtest

uptrend="20210715-20211118"
downtrend="20211118-20220515"
mm2021="20210515-20220515"
up="20210127-20210221"
down="20210509-20210524"
side="20210518-20210610"

__volume='user_data'

function __parse_strategy(){

	__config="$__volume/configs/bt/basic.json";
	__strategy_cmd="--strategy $1"

	case $1 in
		Heracles)
			__config="$__volume/configs/bt/heracles.json";
			shift
		;;

		GodStra)
			__config="$__volume/configs/bt/godstra.json";
			shift
		;;
		*)
			shift
		;;
	esac;
}

__parse_args()
	[[ -z ${__parsed_args} ]] && __parsed_args=true || return 0;

	__cmd_prefix=;
	__timerange=;
	__args=();

	while [[ $# -gt 0 ]]; do
		case $1 in
			--echo)
				__cmd_prefix=echo;
				shift
			;;

			--strategy)
				__parse_strategy $2
				shift
				shift
			;;
			--uptrend)
				__timerange="--timerange $uptrend"
				shift
			;;
			--downtrend)
				__timerange="--timerange $downtrend"
				shift
			;;
			--up)
				__timerange="--timerange $up"
				shift
			;;
			--down)
				__timerange="--timerange $down"
				shift
			;;
			--side)
				__timerange="--timerange $side"
				shift
			;;
			--mm2021)
				__timerange="--timerange $mm2021"
				shift
			;;

			*)
				__args+=($1);
				shift
			;;
		esac;
	done;

__parse_args
${__cmd_prefix} freqtrade backtesting --config ${__config} ${__timerange}  $__strategy_cmd ${__args[@]} 